name: Deploy to VPS

on:
  push:
    branches: [ main, master ]  # Support both main and master
    paths-ignore:
      - '**.md'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PORTFOLIO_GITHUB_TOKEN: ${{ secrets.PORTFOLIO_GITHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            PORTFOLIO_GITHUB_TOKEN=${{ secrets.PORTFOLIO_GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Change these variables for your own deployment
            PROJECT_NAME="portfolio"
            DEPLOY_DIR="/var/www/sam/${PROJECT_NAME}"
            CONTAINER_NAME="${PROJECT_NAME}"
            PORT="3000" 
            
            # Create deployment directory if it doesn't exist
            sudo mkdir -p $DEPLOY_DIR
            sudo chown $USER:$USER $DEPLOY_DIR
            cd $DEPLOY_DIR
            
            # Login to GitHub Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Create or update docker-compose.yml
            cat > docker-compose.yml << 'EOL'
            name: ${PROJECT_NAME}
            services:
              portfolio:
                image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                container_name: ${CONTAINER_NAME}
                ports:
                  - "${PORT}:3000"
                environment:
                  - PORTFOLIO_GITHUB_TOKEN=${PORTFOLIO_GITHUB_TOKEN}
                restart: unless-stopped
            EOL
            
            # Create or update .env file
            echo "PORTFOLIO_GITHUB_TOKEN=${{ secrets.PORTFOLIO_GITHUB_TOKEN }}" > .env
            echo "PORT=${PORT}" >> .env
            
            # Stop and remove any existing containers with the same name
            docker stop ${CONTAINER_NAME} || true
            docker rm ${CONTAINER_NAME} || true
            
            # Pull the latest images and deploy
            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d 